### ISSUE TITLE
DanceTrack training config

### ISSUE THREAD

**Issue by Robotmurlock** [TrackingLaboratory/CAMELTrack#19]
Hey,

Config `cameltrack_train.yaml` is not currently available on this Github repository, so the following command does not work without any modifications:
```bash
uv run tracklab -cn cameltrack_train dataset=dancetrack
```

Is it possible to provide this config or give instructions on how to modify the existing `cameltrack.yaml` file?

**Comment by Robotmurlock** [comment]
Hey,

Thanks for providing the config. Based on the manuscript's text, I changed max epochs from 2 to 10 epochs (does not make a big difference). I obtained around 62 HOTA without training each TE without GAFFE first, which is relatively close. The training pipeline works very well.

I suppose that I have to pretrain TEs to obtain around 65 HOTA (as reported in the paper), or just tune the inference parameters better?

**Comment by bstandaert** [comment]
You can also load some specific weights for each submodule by specifying the `checkpoint_path`. By example, I want to train a GAFFE + finetune TE on DanceTrack by starting from the weights of SportsMOT: 

```
CAMEL:
  _target_: cameltrack.CAMEL
  gaffe:
    ...
    checkpoint_path: null  # random init
  temporal_encoders:
    app_encoder:
      checkpoint_path: "${model_dir}/camel/camel_bbox_app_kps_sportsmot.ckpt"
      ...
    kp_encoder:
      checkpoint_path: "${model_dir}/camel/camel_bbox_app_kps_sportsmot.ckpt"
      ...  
    bbox_encoder:
      checkpoint_path: "${model_dir}/camel/camel_bbox_app_kps_sportsmot.ckpt"
      ...
```
